version: '3.4'

services:
  zungoliant:
    image: zungoliant
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - mongonetwork
    volumes:
      - zvolume:/zungoliant
    environment:
      - CONN_STR=mongodb://root:secret@mongodb
  
volumes:
  zvolume:

networks:
  mongonetwork:
    name: maboke_network  
    external: true 