version: '3.4'

services:
  zungoliant:
    image: zungoliant
    build:
      context: .
      dockerfile: ./Dockerfile
    #ports:
    #  - 3000:8080
    volumes:
      - zvolume:/zungoliant
volumes:
  zvolume: