version: '3.4'

services:
  zungoliant:
    image: zungoliant
    build:
      context: .
      dockerfile: ./Dockerfile
    #depends_on:
   #   - mongo
    networks:
      - mongonetwork
    volumes:
      - zvolume:/zungoliant
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
      ME_CONFIG_MONGODB_URL: mongodb://root:secret@mongo:27017/

volumes:
  zvolume:

networks:
  mongonetwork:
    name: maboke_network  
    external: true 