version: '3.4'

services:
  zungoliant:
    image: zungoliant
    build:
      context: .
      dockerfile: ./Dockerfile
    #ports:
    #  - 3000:8080
    volumes:
      - zvolume:/zungoliant
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
      ME_CONFIG_MONGODB_URL: mongodb://root:secret@mongo:27017/
  mongodb:
    image: mongo
    restart: always
    container_name: mongo-docker
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: maboke
    volumes:
      - maboke-mongo-data:/data/db
volumes:
  zvolume:
  maboke-mongo-data: 