FROM gcc:latest
WORKDIR /zungoliantenv
COPY . ../lib/*
RUN pwd
#RUN apt-get update && apt-get -y install sudo
#RUN cd lib/myhtml && make clean && make && make test && make install
#RUN sudo ldconfig
